const defaultOptions = {
	formatName: 'Schüler heute',
	schoolName: 'hh5872',
	date: 20200106,
	dateOffset: 0,
	strikethrough: true,
	mergeBlocks: true,
	showOnlyFutureSub: false,
	showBreakSupervisions: false,
	showTeacher: true,
	showClass: true,
	showHour: true,
	showInfo: true,
	showRoom: true,
	showSubject: true,
	groupBy: 1,
	hideAbsent: true,
	departmentIds: [],
	departmentElementType: -1,
	hideCancelWithSubstitution: true,
	hideCancelCausedByEvent: false,
	showTime: true,
	showSubstText: true,
	showAbsentElements: [],
	showAffectedElements: [1],
	showUnitTime: true,
	showMessages: true,
	showStudentgroup: false,
	enableSubstitutionFrom: true,
	showSubstitutionFrom: 1800,
	showTeacherOnEvent: false,
	showAbsentTeacher: true,
	strikethroughAbsentTeacher: false,
	activityTypeIds: [2, 3, 4],
	showEvent: false,
	showCancel: true,
	showOnlyCancel: false,
	showSubstTypeColor: false,
	showExamSupervision: false,
	showUnheraldedExams: false,
}
export { defaultOptions }
